version: '3'
services:
  kafka-connect-ui:
    build:
      context: ..
      dockerfile: Dockerfile
    image: parrotstream/kafka-connect-ui:0.9.2
    networks:
    - hadoop
    ports:
    - 8000:8000
    environment:
      CONNECT_URL: http://kafka-connect:8083
networks:
  default:
    external:
      name: hadoop
  hadoop:
    driver: bridge
